telegram_token: "7303997505:AAHHEQG9tu-p5xQKQbdq9XvxlcylKUqS_dA"
channel_id: "" #If you want to force the user to join the channel, please provide your channel's numeric ID (-1243423432). Otherwise, put Empty

panels:
  - url: https://ir.holyalbert.com:10200/albertpanel/
    username: mohammadali
    password: M.s09121249392!
  
  # - url: https://web.example.com:54321
  #   username: admin
  #   password: admin
