start_msg: |

      برای اینکه اطلاعاتت رو ببینی میتونی یکی از اینارو بفرستی

      QrCode - UUID - link
     

help_msg: |
      نسبت به اینکه چه نرم افزاری نصب داری فرق میکنه...
      اگ نمیدونی چجوری پیداش کنی روی /what بزن

channel_msg: |
      کاربر گرامی لطفا برای استفاده از ربات ، ابتدا در کانال زیر عضو شوید 👀 
      🆔 @your_channel_id
      و سپس دوباره دستور /start را ارسال کنید

not_found: "<b> :( اطلاعات اکانت شما پیدا نشد!</b> "
acc_info: 💠 اطلاعات سرویس شما تا این لحظه 💠
whatapp_msg: چه نرم افزاری استفاده میکنید؟

qrcode: لطفا لینک اکانت را ارسال کنید
